Rules
witseie-elen4010/2022-group-lab-001 pull request #81
Opened 2022-05-31 17:55 UTC by GiaCroock

closes #77

2022-05-31 18:02 UTC, raelware requested changes
Good job on making Splash screen  informative. Please see requested change

2022-05-31 18:02 UTC, raelware commented on src/views/multiPlayer.html
> +            <p style="color: black;">Guess a 5 letter word and enter it via the onscreen keyboard or via your physical keyboard.<br>
Please change this to give the instructions on the two types of multiplayer setup

2022-06-01 08:07 UTC, GiaCroock commented on src/views/multiPlayer.html
> +            <p style="color: black;">Guess a 5 letter word and enter it via the onscreen keyboard or via your physical keyboard.<br>
I have changed the multi-player instructions please check if you are happy with them

2022-06-01 11:19 UTC, raelware requested changes
Please see requested changes. When i pulled it down i saw you have instructions on the front screen as well as in the pop up. please remove the ones on the front screen

2022-06-01 11:19 UTC, raelware commented on src/views/multiPlayer.html
> +        This player should then share the game ID with two other person.  <br> The second and third player must click on "JOIN a Game" and enter the Game ID they
It says "two other person", please change this to two other people

2022-06-01 11:19 UTC, raelware commented on src/views/multiPlayer.html
> +        <h4> Option 1: Two Player Game - Guessing the word of the day</h4>
please change this from word the day to just correct word because it is not necessarily the word of the day

2022-06-01 11:56 UTC, GiaCroock commented on src/views/multiPlayer.html
> +        This player should then share the game ID with two other person.  <br> The second and third player must click on "JOIN a Game" and enter the Game ID they
Done

2022-06-01 17:49 UTC, raelware approved these changes

2022-06-01 17:50 UTC, merged